<?php

namespace CV\Bundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CVDomaineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CVDomaineRepository extends EntityRepository
{
}
