<?php

namespace CV\Bundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * CVRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CVRepository extends EntityRepository
{
  public function getCVs($page,$nbPerPage)
  {
    $query = $this->createQueryBuilder('a')
        ->leftJoin('a.image', 'i')
        ->addSelect('i')
        ->leftJoin('a.domaines', 'c')
        ->addSelect('c')
        ->orderBy('a.date', 'DESC')
        ->getQuery()
    ;

    $query
        ->setFirstResult(($page-1) * $nbPerPage)
        ->setMaxResults($nbPerPage)
    ;

    return new Paginator($query, true);
  }
}
